#
#Fri Dec 26 15:03:02 ART 2025
model.directory=C\:\\Users\\lmayo\\gitlocal\\endomembraneSystem\\immunity
host.0.type=LOCAL
batch.param.file=C\:\\Users\\lmayo\\gitlocal\\endomembraneSystem\\immunity\\batch\\batch_params.xml
poll.frequency=1.0
scenario.directory=C\:\\Users\\lmayo\\gitlocal\\endomembraneSystem\\immunity\\immunity.rs
param.file=C\:\\Users\\lmayo\\gitlocal\\endomembraneSystem\\immunity\\immunity.rs\\parameters.xml
key.directory=C\:\\Users\\lmayo/.ssh
host.0.instances=6
output.directory=C\:\\Users\\lmayo\\gitlocal\\endomembraneSystem\\immunity\\output
vm.arguments=-Xss10M -Xmx600M -Djava.library.path\=C\:\\Users\\lmayo\\gitlocal\\endomembraneSystem\\immunity/lib -Dfile.encoding\=windows-1252 -Dstdout.encoding\=windows-1252 -Dstderr.encoding\=windows-1252
